CREATE DATABASE `MIRACLE_CAT`;

DROP TABLE `MEMBER`;
CREATE TABLE `MEMBER` (
    `MEMBER_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '회원 아이디',
    `EMAIL` varchar(100) NOT NULL COMMENT '사용자 아이디',
    `PASSWORD` varchar(64) NOT NULL COMMENT '비밀번호',
    `NAME` varchar(20) NOT NULL COMMENT '사용자 이름',
    `ZIP_CODE` varchar(10) DEFAULT NULL COMMENT '우편번호',
    `ADDRESS` varchar(255) DEFAULT NULL COMMENT '사용자 주소',
    `CELL_PHONE` varchar(20) DEFAULT NULL COMMENT '연락처',
    `CREATED_AT` datetime NOT NULL COMMENT '가입 일시',
    `LAST_UPDATED_ID` bigint(20) DEFAULT NULL COMMENT '최종 수정자 아이디',
    `LAST_UPDATED_AT` datetime DEFAULT NULL COMMENT '최종 수정 일시',
    PRIMARY KEY (`MEMBER_ID`),
    UNIQUE KEY `UK_MEMBER_EMAIL` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='회원';

INSERT INTO MEMBER (MEMBER_ID,EMAIL,PASSWORD,NAME,ZIP_CODE,ADDRESS,CELL_PHONE,CREATED_AT)
VALUES (1,'miracle_1212@naver.com','85189C34F5DF35582DE4EA2208BBDA6EFC5CDE8E0B3C2FC6422A64F4D657BD74','MiracleCat','12345','대한민국','01012341234',NOW());

DROP TABLE `NOTICE`;
CREATE TABLE `NOTICE` (
    `NOTICE_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '공지사항아이디',
    `TITLE` varchar(64) NOT NULL COMMENT '제목',
    `CONTENT` text NOT NULL COMMENT '내용',
    `OPEN` char(1) CHARACTER SET latin1 NOT NULL DEFAULT 'Y' COMMENT '공개여부',
    `CREATED_ID` bigint(20) NOT NULL COMMENT '등록자',
    `CREATED_AT` datetime NOT NULL COMMENT '등록일자',
    `LAST_UPDATED_ID` bigint(20) DEFAULT NULL COMMENT '수정자',
    `LAST_UPDATED_AT` datetime DEFAULT NULL COMMENT '수정일자',
    PRIMARY KEY (`NOTICE_ID`),
    KEY `FK_NOTICE_CREATED` (`CREATED_ID`),
    KEY `FK_NOTICE_LAST_UPDATED` (`LAST_UPDATED_ID`),
    CONSTRAINT `FK_NOTICE_CREATED` FOREIGN KEY (`CREATED_ID`) REFERENCES `MEMBER` (`MEMBER_ID`),
    CONSTRAINT `FK_NOTICE_LAST_UPDATED` FOREIGN KEY (`LAST_UPDATED_ID`) REFERENCES `MEMBER` (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='공지사항관리';

